allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': true
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/nodemailer@8.0.2'
