export const CONTENT_PREVIEW_GRPC_CLIENT = 'CONTENT_PREVIEW_GRPC_CLIENT';
export const CONTENT_PREVIEW_GRPC_DEADLINE_MS = 300;

export const CONTENT_PREVIEW_GRPC_PACKAGE = 'content.preview.v1';
export const CONTENT_PREVIEW_GRPC_SERVICE = 'ContentPreviewService';
export const CONTENT_PREVIEW_GRPC_ANALYZE_METHOD = 'Analyze';
export const CONTENT_PREVIEW_GRPC_DEFAULT_URL = '127.0.0.1:50051';
