export const IMAGE_PROCESSING_ERROR_CODES = {
  INVALID_IMAGE: 'INVALID_IMAGE',
  UNSUPPORTED_IMAGE_FORMAT: 'UNSUPPORTED_IMAGE_FORMAT',
  MULTI_FRAME_IMAGE: 'MULTI_FRAME_IMAGE',
  IMAGE_TOO_SMALL: 'IMAGE_TOO_SMALL',
  IMAGE_PIXEL_LIMIT_EXCEEDED: 'IMAGE_PIXEL_LIMIT_EXCEEDED',
} as const;
